modules/security/partials/iam-policies.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2633 
https://deploy-preview-13--rp-cloud.netlify.app/redpanda-cloud/security/authorization/cloud-iam-policies-azure/

clarify Azure permissions

---

modules/reference/partials/tiers.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2639
Review deadline: Aug 2
https://deploy-preview-14--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/?tab=tabs-1-azure

BYOC support in Azure eastus2

---

modules/get-started/pages/cluster-types/byoc/create-byoc-cluster-azure.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-446
Review deadline: Aug 8
[Azure prereqs](https://deploy-preview-19--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/create-byoc-cluster-azure/)

Azure prereqs should include SKU restrictions

---

modules/get-started/pages/whats-new-cloud.adoc
modules/reference/partials/tiers.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2666
Review deadline: 15th Aug
[What's new](https://deploy-preview-25--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/#support-for-additional-regions)
[BYOC Tiers](https://deploy-preview-25--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/?tab=tabs-1-amazon-web-services-aws#byoc-supported-regions)
[Dedicated Tiers](https://deploy-preview-25--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/dedicated-tiers/?tab=tabs-1-amazon-web-services-aws#dedicated-supported-regions)

Re-add cloud region me-central-1

---

.github/workflows/build.yml

jira: https://redpandadata.atlassian.net/browse/PESDLC-1720
no functionality change.
N/A

gha: use oidc

---

modules/networking/pages/cloud-security-network.adoc
modules/security/pages/cloud-authentication.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2662
Review deadline: Aug 15
[Cloud SSO - Integrate with Microsoft Entra ID](https://deploy-preview-24--rp-cloud.netlify.app/redpanda-cloud/security/cloud-authentication/#single-sign-on) 
[South-North network ports](https://deploy-preview-24--rp-cloud.netlify.app/redpanda-cloud/networking/cloud-security-network/#south-north)

cloud SSO for Azure

---

modules/get-started/pages/cloud-overview.adoc

connectors: added managed connectors to shared responsibility model

---

modules/networking/pages/aws-privatelink.adoc
modules/networking/pages/azure-private-link.adoc
modules/networking/partials/private-links-api-access-token.adoc
modules/security/pages/cloud-authentication.adoc

Use 'jq -r' instead of sed to remove quotes

---

modules/get-started/pages/cluster-types/byoc/vpc-byo-aws.adoc

* Adds the rpk validation output to the sample.
* Adds an explanation of what the validation will be checking.
* Adds instructions for bypassing validation.

Add information about rpk validation

---

modules/get-started/pages/cloud-overview.adoc
modules/manage/pages/api/cloud-api-errors.adoc

fix extra column

---

modules/get-started/pages/cluster-types/byoc/create-byoc-cluster-azure.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2721
Review deadline: Sept 13
[BYOC on Azure Prerequisites](https://deploy-preview-56--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/create-byoc-cluster-azure/#prerequisites)

add Azure Network Watcher as prereq

---

modules/get-started/pages/cluster-types/byoc/create-byoc-cluster-azure.adoc
modules/get-started/pages/cluster-types/dedicated/create-dedicated-cloud-cluster.adoc
modules/networking/pages/azure-private-link.adoc

Adds our feature flag admonition to pages for Azure for BYOC & Dedicated + Azure Private Link
Based on [this thread](https://redpandadata.slack.com/archives/C0191NM4WU9/p1725418000149899).
Review deadline: Sept 5
[Create BYOC](https://deploy-preview-46--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/create-byoc-cluster-azure/)
[Create Dedicated](https://deploy-preview-46--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/dedicated/create-dedicated-cloud-cluster/)
[Configure Azure Private Link](https://deploy-preview-46--rp-cloud.netlify.app/redpanda-cloud/networking/azure-private-link/)

add FF admonition for Azure

---

modules/ROOT/nav.adoc
modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc
modules/get-started/pages/whats-new-cloud.adoc

Resolves n/a
Review deadline: none
https://deploy-preview-51--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/remote-read-replicas/

Add remote read replica instructions for BYOVPC

---

modules/develop/pages/consume-data/follower-fetching.adoc

Fix syntax

---

modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc

DOC-589 Update remote-read-replicas.adoc

---

.github/workflows/update-extensions.yml

jira: [PESDLC-1579]
follow-up to PR #21, updates `update-extensions` to use oidc
N/A
[PESDLC-1579]: https://redpandadata.atlassian.net/browse/PESDLC-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

gha: update update-extensions to use oidc

---

modules/reference/partials/tiers.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-586
Review deadline: Oct 3
https://deploy-preview-81--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/

DOC-586-Update-cloud-tiers-for-GCP

---

modules/ROOT/nav.adoc
modules/develop/pages/managed-connectors/create-sqlserver-connector.adoc

Resolves: https://redpandadata.atlassian.net/browse/CIAINFRA-452

connectors: added docs for SQL Server (Debezium) connector

---

modules/get-started/pages/cluster-types/byoc/create-byoc-cluster-azure.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-462
Resolves https://redpandadata.atlassian.net/browse/DOC-631
This adds steps to enable Kafka Connectors for BYOC clusters running on Azure. 
Review deadline: Oct 10
https://deploy-preview-85--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/create-byoc-cluster-azure/#enable-kafka-connect

DOC-462 Azure Kafka Connectors

---

modules/get-started/pages/cluster-types/byoc/create-byoc-cluster-azure.adoc

This adds to Azure quota prereqs + updates the style of the prereqs to make it a bit easier to digest. 
Resolves https://redpandadata.atlassian.net/browse/DOC-538
Review deadline: Friday Oct 18
[Create a BYOC Cluster on Azure - Prereqs](https://deploy-preview-92--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/create-byoc-cluster-azure/)

Update Azure quotas for additional node families

---

modules/get-started/pages/whats-new-cloud.adoc
modules/reference/partials/tiers.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-377
Review deadline: Oct 30
[What's New in Redpanda Cloud](https://deploy-preview-100--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/)
[BYOC Tiers (in note)](https://deploy-preview-100--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/)

DOC-377 cost-optimized cloud tiers

---

modules/ROOT/nav.adoc
modules/billing/pages/aws-commit.adoc
modules/billing/pages/azure-commit.adoc
modules/billing/pages/gcp-commit.adoc
modules/get-started/pages/cloud-overview.adoc
modules/get-started/pages/whats-new-cloud.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-670
Review deadline: Not sure when this will release: Oct 31? 
[Use Azure Commitments](https://deploy-preview-99--rp-cloud.netlify.app/redpanda-cloud/billing/azure-commit/)
[Cloud Overview - Sign up for Dedicated](https://deploy-preview-99--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#sign-up-for-dedicated)

DOC-670 Azure Marketplace Dedicated

---

modules/develop/pages/connect/connect-quickstart.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/105
Review deadline: 01 November
Limit message added to the Before you start section.
[Quickstart](https://deploy-preview-106--rp-cloud.netlify.app/redpanda-cloud/develop/connect/connect-quickstart/)

DOC-696 Add note about 10 pipeline limit

---

modules/get-started/pages/cloud-overview.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-692
https://deploy-preview-132--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/

DOC-692 remove extra word

---

local-antora-playbook.yml
modules/ROOT/nav.adoc
modules/develop/pages/connect/components/inputs/pg_stream.adoc

Review deadline: 2nd December
[pg_stream input](https://deploy-preview-140--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/pg_stream/)

DOC-699 Add pg_stream to Cloud docs

---

modules/manage/pages/terraform-provider.adoc

Add rpcn limitation to tf provider

---

local-antora-playbook.yml
modules/ROOT/nav.adoc
modules/develop/pages/connect/components/inputs/pg_stream.adoc
modules/develop/pages/connect/components/inputs/postgres_cdc.adoc

Review deadline: 5th December
[postgres_cdc](https://deploy-preview-145--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/postgres_cdc/)

DOC-814 Rename pg_stream input

---

.github/workflows/update-extensions.yml

Merge extension updates automatically

---

modules/security/partials/iam-policies.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-764
Review deadline: Dec 11
[AWS IAM Policies](https://deploy-preview-152--rp-cloud.netlify.app/redpanda-cloud/security/authorization/cloud-iam-policies/)
[Azure IAM Policies](https://deploy-preview-152--rp-cloud.netlify.app/redpanda-cloud/security/authorization/cloud-iam-policies-azure/)
[GCP IAM Policies](https://deploy-preview-152--rp-cloud.netlify.app/redpanda-cloud/security/authorization/cloud-iam-policies-gcp/)

DOC-764 clarify BYOC vs BYOVPC policies

---

modules/get-started/pages/cloud-overview.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-765
Review deadline: Dec 12
[Shared responsibility model](https://deploy-preview-153--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#shared-responsibility-model)

DOC-765 BYOVPC link to shared responsibility

---

modules/get-started/pages/cloud-overview.adoc
modules/get-started/pages/cluster-types/byoc/aws/create-byoc-cluster-aws.adoc
modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
modules/get-started/pages/whats-new-cloud.adoc
modules/shared/partials/feature-flag.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-807
[Create a BYOVPC Cluster on AWS](https://deploy-preview-146--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/vpc-byo-aws/)

BYOVPC AWS follow-up

---

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc

Aligning with changes in BYOVPC Azure around bearer token.

Update vpc-byo-aws.adoc: Change YOUR_TOKEN to ${BEARER_TOKEN}

---

modules/get-started/pages/cloud-overview.adoc
modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc
modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc
modules/get-started/pages/cluster-types/byoc/gcp/create-byoc-cluster-gcp.adoc
modules/get-started/pages/cluster-types/byoc/gcp/vpc-byo-gcp.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-792
Review deadline: Dec 17
[Create a BYOVPC Cluster on Azure](https://deploy-preview-149--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/azure/vnet-azure/)

DOC-792 BYO VNET phase 2

---

modules/develop/pages/connect/configuration/resource-management.adoc

Resolves [DOC-877](https://redpandadata.atlassian.net/browse/DOC-877)
Review deadline: 18th December
https://deploy-preview-160--rp-cloud.netlify.app/redpanda-cloud/develop/connect/configuration/resource-management/
[DOC-877]: https://redpandadata.atlassian.net/browse/DOC-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-877 Manage pipeline resources fix

---

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc

Small improvement to validation steps where we use the ENV variable used from previous steps instead of having the user enter the operation_id manually in the docs.

Update vpc-byo-aws.adoc - Small enhancement to BYOVPC AWS cluster validation

---

modules/ROOT/nav.adoc
modules/develop/pages/connect/configuration/contextual-variables.adoc
modules/develop/pages/connect/connect-quickstart.adoc

Resolves [DOC-621](https://redpandadata.atlassian.net/browse/DOC-621)
Review deadline: 10th January
Also related PR: https://github.com/redpanda-data/rp-connect-docs/pull/140
[Contextual variables](https://deploy-preview-165--rp-cloud.netlify.app/redpanda-cloud/develop/connect/configuration/contextual-variables/)
[Quickstart](https://deploy-preview-165--rp-cloud.netlify.app/redpanda-cloud/develop/connect/connect-quickstart/)
[DOC-621]: https://redpandadata.atlassian.net/browse/DOC-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-621 Contextual variables

---

modules/security/partials/iam-policies.adoc

Add changes introduced [here](https://github.com/redpanda-data/cloudv2/pull/20029/files#r1883720037)
- [x ] Content gap

update IAM policy with EKS permissions

---

modules/manage/pages/terraform-provider.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2808
Review deadline: 9 January
https://deploy-preview-164--rp-cloud.netlify.app/redpanda-cloud/manage/terraform-provider/

DOC-864 Updates for Terraform provider 0.10

---

modules/develop/pages/connect/configuration/resource-management.adoc
modules/develop/pages/connect/configuration/secret-management.adoc
modules/develop/pages/connect/connect-quickstart.adoc
modules/develop/partials/availability-message.adoc

Review deadline: 10th January
- [Overview](https://deploy-preview-162--rp-cloud.netlify.app/redpanda-cloud/develop/connect/about/)
- [Quickstart](https://deploy-preview-162--rp-cloud.netlify.app/redpanda-cloud/develop/connect/connect-quickstart/?tab=tabs-1-serverless-standard)
- [Secret Management](https://deploy-preview-162--rp-cloud.netlify.app/redpanda-cloud/develop/connect/configuration/secret-management/)

DOC-888 Add Serverless Pro to RPCN content

---

modules/get-started/pages/whats-new-cloud.adoc
modules/reference/partials/tiers.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-708
Review deadline: Nov 27
[BYOC tiers](https://deploy-preview-123--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/)
[Dedicated tiers](https://deploy-preview-123--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/dedicated-tiers/)
[What's New](https://deploy-preview-123--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/)
[Dedicated regions for Azure](https://deploy-preview-123--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/dedicated-tiers/)

add tier 4 for Azure

---

modules/networking/pages/azure-private-link.adoc

Changing yes to true in Azure PrivateLink docs

---

local-antora-playbook.yml
modules/ROOT/nav.adoc
modules/develop/pages/connect/cookbooks/snowflake_ingestion.adoc

Resolves DOC-973
Review deadline: 27th January
[Ingest data into Snowflake](https://deploy-preview-184--rp-cloud.netlify.app/redpanda-cloud/develop/connect/cookbooks/snowflake_ingestion/)

DOC-973 Add snowflake cookbook page

---

local-antora-playbook.yml
modules/ROOT/nav.adoc
modules/develop/pages/connect/components/processors/ollama_moderation.adoc

Resolves [DOC-927](https://redpandadata.atlassian.net/browse/DOC-927)
Review deadline: 21st January
[ollama_moderation processor](https://deploy-preview-179--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/processors/ollama_moderation/)
[DOC-927]: https://redpandadata.atlassian.net/browse/DOC-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-927 Add ollama_moderation processor

---

modules/get-started/pages/cluster-types/dedicated/quick-start-cloud.adoc

Adding some changes based on my recent spin on RP Dedicated

Update quick-start-cloud.adoc - Small changes

---

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc
modules/networking/pages/azure-private-link.adoc

Add jq to pre-requisites

---

modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc

This pull request updates the required vCPU specifications for the Azure subscription used with Redpanda.
Resolves https://redpandadata.atlassian.net/browse/DOC-1052
[Check Azure quota](https://deploy-preview-222--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/azure/create-byoc-cluster-azure/#check-azure-quota)

DOC-1052 update instance types for BYOC on Azure

---

modules/get-started/pages/cloud-overview.adoc

- [ X] Small fix (typos, links, copyedits, etc)

Update cloud-overview.adoc Updated number of connectors

---

.hyperlint/config.yaml
.hyperlint/reviewer/custom-style-guide/code-formatting.adoc
.hyperlint/reviewer/custom-style-guide/grammar.adoc
.hyperlint/reviewer/custom-style-guide/styles.adoc
.hyperlint/reviewer/vale-style-guide/.vale.ini
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/MeaningfulLinkText.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/OptionalPlurals.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/SentenceLength.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/SwapWords.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/We.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/WeakModifiers.yml
.hyperlint/reviewer/vale-style-guide/styles/config/vocabularies/CustomVocab/accept.txt
.hyperlint/reviewer/vale-style-guide/styles/config/vocabularies/CustomVocab/reject.txt

Add Styles

---

modules/ROOT/nav.adoc
modules/develop/pages/agents/about.adoc
modules/develop/pages/agents/create-support-agent.adoc
modules/get-started/pages/whats-new-cloud.adoc
modules/shared/partials/feature-flag-agents.adoc

Resolves [DOC-1170](https://redpandadata.atlassian.net/browse/DOC-1170)
Review deadline: 4th April
- [AI Agents](https://deploy-preview-250--rp-cloud.netlify.app/redpanda-cloud/develop/agents/about/)
- [Create a Support Agent](https://deploy-preview-250--rp-cloud.netlify.app/redpanda-cloud/develop/agents/create-support-agent/)
- [What's new](https://deploy-preview-250--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/)
[DOC-1170]: https://redpandadata.atlassian.net/browse/DOC-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1170 Add AI Agents docs

---

modules/get-started/pages/cluster-types/byoc/aws/create-byoc-cluster-aws.adoc

Resolves confusion with customer needing who believes they create their own IAM policies as opposed to rpk.

BYOC - AWS IAM clarification

---

modules/get-started/pages/cloud-overview.adoc
modules/get-started/pages/whats-new-cloud.adoc
modules/reference/partials/tiers.adoc

Document the doubled partition limits in v25.1
Resolves https://redpandadata.atlassian.net/browse/DOC-268
Review deadline: Will merge after 25.1 releases ~March 25
[What's New in Redpanda Cloud](https://deploy-preview-200--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/)
[Cloud Overview](https://deploy-preview-200--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/)
[BYOC tiers](https://deploy-preview-200--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/), [Dedicated tiers](https://deploy-preview-200--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/dedicated-tiers/)

DNM - tiers: Update partition limits

---

modules/billing/pages/billing.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-1214
https://deploy-preview-254--rp-cloud.netlify.app/redpanda-cloud/billing/billing/

DOC-1214 update link to price calculator

---

modules/get-started/pages/byoc-arch.adoc
modules/get-started/pages/cloud-overview.adoc
modules/get-started/pages/whats-new-cloud.adoc
modules/shared/partials/feature-flag-agents.adoc

This pull request includes updates the What's New to say data transforms GA pertains to BYOC and Dedicated. It also updates the documentation for Bring Your Own Cloud (BYOC) clusters in Redpanda. The changes primarily focus on improving clarity and providing additional details about the architecture and setup of BYOC clusters.
* Added an introductory explanation of BYOC clusters, highlighting the benefits of deploying Redpanda in your own cloud environment for enhanced security and isolation.
* Clarified the differences between the control plane and data plane in the Redpanda Cloud UI, providing specific navigation details to help users identify which plane they are in.
* Updated the number of fully-managed cloud cluster types from four to three, reflecting the current offerings.
* …

DOC-1226 overview style edits

---

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc

Correcting small formatting and typo. 

Update vpc-byo-aws.adoc - Small formatting and TYPO

---

modules/get-started/pages/whats-new-cloud.adoc

This pull request updates the "What's New in Redpanda Cloud" documentation to include details about a new feature and an additional supported region.
The updates to Iceberg content pertaining to the Azure beta are in https://github.com/redpanda-data/docs/pull/1123
New feature documentation:
* Added a section about the beta support for Iceberg topics on BYOC clusters in Azure, with a link to the relevant documentation (`modules/get-started/pages/whats-new-cloud.adoc`).
Review deadline: 14 May
[What's New in Cloud > May 2025](https://deploy-preview-293--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/#may-2025)

Iceberg beta - Azure

---

modules/develop/partials/availability-message.adoc
modules/get-started/pages/cloud-overview.adoc
modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc
modules/get-started/pages/whats-new-cloud.adoc
modules/shared/partials/feature-flag-rpcn.adoc

This pull request introduces updates related to Redpanda Connect, primarily focusing on its availability and configuration for BYOVPC clusters on Azure. These changes include documentation updates and feature flag adjustments.
* [`modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc`](diffhunk://#diff-83e23f48f04bb841f52bad086df6cddaf7be01927366dbe59f4644390c60a804R195-R196): Added instructions to disable Redpanda Connect by modifying the `byoc.auto.tfvars.json` file and removing associated security groups and instance profiles.
* [`modules/get-started/pages/whats-new-cloud.adoc`](diffhunk://#diff-825e3d404929927e196111eaa92a310ee71d39aa9310418f56a55099a3a3f7c3R18-R21): Announced the beta availability of Redpanda Connect for BYOVPC clusters on Azure in the "What's New" …

Add RPCN on Azure BYOVPC to What's New

---

modules/manage/pages/terraform-provider.adoc

Update terraform-provider.adoc - Update to use new Organization IAM page
