redpanda-data/cloud-docs

.github/workflows/build.yml
fixes: https://redpandadata.atlassian.net/browse/PESDLC-1539
N/A
=> gha: use aws sm

modules/manage/pages/api/cloud-api-authentication.adoc, modules/manage/pages/api/cloud-api-quickstart.adoc, modules/manage/pages/api/cloud-dataplane-api.adoc, modules/manage/partials/controlplane-api.adoc, package-lock.json
Resolves https://github.com/redpanda-data/documentation-private/issues/2629
Review deadline: 1 Aug
This is a copy of the changes added in https://github.com/redpanda-data/docs/pull/657 from the main repo.
[API quickstart (serverless)](https://deploy-preview-10--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-api-quickstart/?tab=tabs-1-serverless)
[Use Control Plane API with Serverless](https://deploy-preview-10--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-serverless-controlplane-api/)
=> Move serverless API doc updates to new repo

modules/get-started/pages/cluster-types/byoc/create-byoc-cluster-azure.adoc
**Old:**
> - Resources: The Azure subscription must be registered for the following resource providers. For more information, see the [Microsoft documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types).
>   - Microsoft.Compute
>   - Microsoft.ManagedIdentity
>   - Microsoft.Storage
>   - Microsoft.KeyVault
>   - Microsoft.Network
>   - Microsoft.Compute.EncryptionAtHost
**New:**
> - Resources: The Azure subscription must be registered for the following resource providers. For more information, see the [Microsoft documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types).
>   - Microsoft.Compute
>   - Microsoft.ManagedIdentity
>   - Microsoft.Storage
>   - …
=> create-byoc-cluster-azure: Microsoft.Compute/EncryptionAtHost is a feature, not a resource provider

modules/security/pages/cloud-authentication.adoc
Resolves https://github.com/redpanda-data/documentation-private/issues/2661 
[User authentication/SSO](https://deploy-preview-20--rp-cloud.netlify.app/redpanda-cloud/security/cloud-authentication/)
=> remove feature flag for SSO user authentication

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/whats-new-cloud.adoc
Changes self-hosted to Self-Managed + consolidates the new features in July for Serverless (which came in separately initially). 
[Overview](https://deploy-preview-22--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#redpanda-cloud-vs-self-managed-feature-compatibility)
[What's New in Cloud](https://deploy-preview-22--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/)
=> edit self-hosted

modules/networking/pages/aws-privatelink.adoc
Resolves https://github.com/redpanda-data/documentation-private/issues/2673
Review deadline: 16 Aug
[Configure AWS PrivateLink with the Cloud API > Configure PrivateLink connection to Redpanda Cloud > Add security group rules](https://deploy-preview-27--rp-cloud.netlify.app/redpanda-cloud/networking/aws-privatelink/#add-security-group-rules)
=> AWS PrivateLink - add security group rule for Console

modules/networking/pages/aws-privatelink.adoc
Resolves https://github.com/redpanda-data/documentation-private/issues/2673
Add field in API request body to enable RP Console
Review deadline: 16 Aug
https://deploy-preview-28--rp-cloud.netlify.app/redpanda-cloud/networking/aws-privatelink/#create-new-cluster-with-privatelink-endpoint-service-enabled
=> Enable console with PrivateLink

modules/networking/partials/private-links-test-connection.adoc
Fix based on https://redpandadata.slack.com/archives/C01LK3UK2K1/p1723839315545359
Review deadline: 19 Aug
[Configure AWS PrivateLink in the Cloud UI](https://deploy-preview-29--rp-cloud.netlify.app/redpanda-cloud/networking/configure-privatelink-in-cloud-ui/#test-the-connection) (this section is single sourced across multiple pages)
=> Add SASL mechanism to private links shell variables

modules/networking/pages/azure-private-link.adoc, modules/networking/partials/private-links-api-access-token.adoc
Minor edits for the Private Link docs based on additional UAT sessions.
Resolves https://github.com/redpanda-data/documentation-private/issues/2687
Review deadline: 23 Aug
[Configure Azure Private Link with the Cloud API](https://deploy-preview-34--rp-cloud.netlify.app/redpanda-cloud/networking/azure-private-link/)
=> Clarify Private Link steps

.github/workflows/update-extensions.yml
Whenever we update our extensions in https://github.com/redpanda-data/docs-extensions-and-macros, we need to remember to manually do npm update @redpanda-data/docs-extensions-and-macros to get the latest changes in all our local builds. This PR adds a GH Action that can be triggered manually or automatically every time a new extension version is released. The action runs npm update @redpanda-data/docs-extensions-and-macros and submits a pull request to the respective branches.
=> Add automation for npm update

.github/workflows/update-extensions.yml
GitHub treats the placeholder email as a user and requires the CLA to be signed. This change sets the user to [vbotbuildovich](https://github.com/vbotbuildovich) which doesn't require this.
=> Update GitHub user

modules/ROOT/nav.adoc, modules/manage/pages/api/cloud-api-quickstart.adoc, modules/manage/partials/controlplane-api.adoc, modules/networking/pages/azure-private-link.adoc, modules/networking/pages/dedicated/vpc-peering.adoc, modules/networking/partials/private-links-api-access-token.adoc
- Add support for Dedicated clusters to Private Link doc
- Add Azure to Cloud API docs
Resolves https://github.com/redpanda-data/documentation-private/issues/2691
Resolves https://github.com/redpanda-data/documentation-private/issues/2692
Review deadline: 28 Aug 2024
[Cloud API Quickstart](https://deploy-preview-38--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-api-quickstart/)
[Use the Control Plane API with BYOC](https://deploy-preview-38--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-byoc-controlplane-api/)
[Configure Azure Private Link with the Cloud API](https://deploy-preview-38--rp-cloud.netlify.app/redpanda-cloud/networking/azure-private-link/)
=> Add Azure to cloud docs

modules/develop/pages/connect/about.adoc, modules/get-started/pages/whats-new-cloud.adoc
Makes sure Data Plane API links are linking to RPCN PipelineService group of endpoints.
Resolves https://github.com/redpanda-data/documentation-private/issues/2540
Review deadline: 11 September if possible
[Redpanda Connect overview](https://deploy-preview-60--rp-cloud.netlify.app/redpanda-cloud/develop/connect/about/)
[What's New](https://deploy-preview-60--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/)
=> 2540 - Fix links to API Data Plane

modules/get-started/pages/cluster-types/byoc/create-byoc-cluster-azure.adoc, modules/manage/pages/schema-reg/edit-topic-configuration.adoc, modules/manage/pages/schema-reg/programmable-push-filters.adoc, modules/manage/pages/schema-reg/record-deserialization.adoc
This clarifies that Azure Network Watcher should be enabled within the NetworkWatcherRG resource group.
https://deploy-preview-59--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/create-byoc-cluster-azure/#check-your-azure-subscription
=> clarify NetworkWatcherRG required

modules/ROOT/nav.adoc, modules/develop/pages/connect/cookbooks/rag.adoc
Adds AI cookbook to Cloud.
Resolves https://github.com/redpanda-data/documentation-private/issues/2540
Review deadline: 11 September
https://deploy-preview-62--rp-cloud.netlify.app/redpanda-cloud/develop/connect/cookbooks/rag/
=> 2540 - Add cookbook to cloud docs

modules/ROOT/nav.adoc, modules/develop/pages/connect/cookbooks/kafka_migrator.adoc
Adds Kafka Migrator cookbook to Cloud.
Resolves https://github.com/redpanda-data/documentation-private/issues/2540
Review deadline: 12 September
=> 2540 Add Kafka Migrator Cookbook to Cloud docs

modules/develop/pages/connect/connect-quickstart.adoc
This adds to quickstart that it's supported on standard BYOC (not customer-managed VPC). See [slack thread](https://redpandadata.slack.com/archives/C02JDTMG8GN/p1726160338114289?thread_ts=1726140145.126409&cid=C02JDTMG8GN).
[Quickstart Prereqs](https://deploy-preview-65--rp-cloud.netlify.app/redpanda-cloud/develop/connect/connect-quickstart/#prerequisites)
=> rpcn not on byovpc

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/whats-new-cloud.adoc
Resolves https://github.com/redpanda-data/documentation-private/issues/2467
Review deadline: Wed Sept 18
[Redpanda Overview - Maintenance windows](https://deploy-preview-68--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#maintenance-windows)
=> DOC-255-Cloud-Upgrades-Maintenance-Windows

modules/ROOT/nav.adoc, modules/billing/pages/aws-pay-as-you-go.adoc, modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/whats-new-cloud.adoc
This adds a page for pay-as-you-go billing on AWS.
This is an extension of https://github.com/redpanda-data/documentation-private/issues/2211
Review deadline: Wed Sept 18
[Use AWS Pay As You Go](https://deploy-preview-67--rp-cloud.netlify.app/redpanda-cloud/billing/aws-pay-as-you-go/)
[Sign up for Dedicated](https://deploy-preview-67--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#sign-up-for-dedicated)
[What's New](https://deploy-preview-67--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/#self-service-sign-up-for-dedicated-on-aws-marketplace)
=> add AWS pay as you go

modules/get-started/pages/cluster-types/serverless.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/manage/partials/controlplane-api.adoc, modules/reference/pages/tiers/index.adoc, modules/reference/partials/tiers.adoc
Resolves https://github.com/redpanda-data/documentation-private/issues/2730
Review deadline: Wed Sept 18
- [BYOC tiers](https://deploy-preview-70--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/) and [Dedicated tiers](https://deploy-preview-70--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/dedicated-tiers/)
- Control Plane API [BYOC](https://deploy-preview-70--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-byoc-controlplane-api/#cluster-tiers) and [Dedicated](https://deploy-preview-70--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-dedicated-controlplane-api/#cluster-tiers)
- [Serverless](https://deploy-preview-70--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless/)
=> DOC-576-change-logical-partitions-to-pre-replication

modules/networking/pages/azure-private-link.adoc
Missing `\` character at end of line of part of a command.
=> Fix Azure Private Link command typo.

modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc
Fixes the following warning in the docs:
```
[17:25:31.660] WARN (asciidoctor): skipping reference to missing attribute: source_cluster_id
file: modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc
source: https://github.com/redpanda-data/cloud-docs (branch: main)
```
The fix was to escape the attribute syntax to tell Antora not to treat that string as an attribute. See https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/#escape-with-backslashes
=> Fix missing attribute warning

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/serverless.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-616
Review deadline: Oct 11
https://deploy-preview-83--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless/
=> DOC-616 Update Serverless doc

local-antora-playbook.yml, modules/develop/pages/connect/components/inputs/redpanda_migrator.adoc, modules/develop/pages/connect/components/inputs/redpanda_migrator_bundle.adoc, modules/develop/pages/connect/components/outputs/redpanda_migrator.adoc, modules/develop/pages/connect/components/outputs/redpanda_migrator_bundle.adoc, modules/develop/pages/connect/components/outputs/redpanda_migrator_offsets.adoc
Resolves https://github.com/redpanda-data/documentation-private/issues/2744
Review deadline: 16 October
See associated PR: https://github.com/redpanda-data/rp-connect-docs/pull/73
Fixes problem with beta tagging of redpanda_migrator components in the Cloud.
Changes to local-antora-playbook.yml must be reversed before merging.
Inputs
[redpanda_migrator](https://deploy-preview-89--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/redpanda_migrator/)
[redpanda_migrator_bundle](https://deploy-preview-89--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/redpanda_migrator_bundle/)
Outputs
[redpanda_migrator](https://deploy-preview-89--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/outputs/redpanda_migrator/) …
=> DOC-600 Fix spacing on redpanda_migrator headers

modules/shared/partials/enterprise-and-console.adoc
=> DOC-648 remove self-hosted in favor of self-managed

modules/networking/pages/cloud-security-network.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-628
Review deadline: Friday Oct 25
https://deploy-preview-97--rp-cloud.netlify.app/redpanda-cloud/networking/cloud-security-network/
=> DOC-628 document TLS for private networking

modules/get-started/pages/cluster-types/byoc/aws/create-byoc-cluster-aws.adoc, modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc, modules/manage/pages/rpk/rpk-install.adoc, modules/security/partials/iam-policies.adoc
This adds a prereqs section to the doc for BYOC on AWS (based on [this slack thread](https://redpandadata.slack.com/archives/C0191NM4WU9/p1729002110977339)).
Resolves https://redpandadata.atlassian.net/browse/DOC-646
Review deadline: Friday Oct 25
[Create a BYOC Cluster on AWS](https://deploy-preview-96--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/create-byoc-cluster-aws/)
=> DOC-646 Document AWS BYOC prereqs

modules/manage/pages/api/cloud-dataplane-api.adoc
Cautions readers to use secrets to inject sensitive information into Create Connector API calls.
This PR also updates the API URLs to
- use the current data plane API version `v1alpha2`
- use `kafka-connect` for connector API urls
(So there is some overlap with #91 )
Review deadline: 5 Nov
[Use the Data Plane APIs > Create a connector](https://deploy-preview-107--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-dataplane-api/#create-a-connector)
=> Using secrets with Kafka Connect Service API

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/outputs/azure_data_lake_gen2.adoc
Review deadline: 30th October
**Change to local playbook must be reverted before merging**
[azure_data_lake_gen2 output](https://deploy-preview-101--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/outputs/azure_data_lake_gen2/)
=> DOC-667 Enable azure_data_lake_gen2 output in Cloud

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/outputs/timeplus.adoc
Resolves: https://github.com/redpanda-data/cloud-docs/pull/new/DOC-667-timeplus_output_cloud
Review deadline: 30th October
[Timeplus output](https://deploy-preview-102--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/outputs/timeplus/)
=> DOC-667 Adds timeplus output to cloud docs

modules/manage/pages/api/cloud-dataplane-api.adoc
The API spec will also be updated with this PR https://github.com/redpanda-data/console/pull/1496
Review deadline: 6 Nov
[Use the Data Plane APIs > Manage Kafka Connect > Create a Kafka Connect connector](https://deploy-preview-110--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-dataplane-api/#create-a-kafka-connect-connector)
=> Secret API requires Base64-encoded value

modules/networking/pages/cloud-security-network.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-171
Review deadline: Friday Nov 8
https://deploy-preview-112--rp-cloud.netlify.app/redpanda-cloud/networking/cloud-security-network/#network-ports
=> Add ports for internal communication

modules/get-started/pages/create-topic.adoc
Documents the new RF=3 enforcement in Redpanda Cloud. 
Resolves https://redpandadata.atlassian.net/browse/DOC-290
Review deadline: Monday Nov 11
[Create a topic](https://deploy-preview-115--rp-cloud.netlify.app/redpanda-cloud/get-started/create-topic/)
See also:
- https://github.com/redpanda-data/docs/pull/840 (for single-sourced content in `docs` repo)
- https://github.com/redpanda-data/docs/pull/841 (for glossary update in `shared` repo)
=> doc cloud minimum replication factor

modules/manage/pages/api/cloud-dataplane-api.adoc
- Adds new section to correctly create a Kafka Connect secret, specifying that the secret has to be Base64-encoded from its JSON format
- Edit the Create a Kafka Connect connector to reference the new section and also explain the `secretManager` syntax used
=> Kafka Connect cluster secret format

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/outputs/snowflake_streaming.adoc
Resolves [DOC-734](https://redpandadata.atlassian.net/browse/DOC-734)
Review deadline: 14 November
Adds `snowflake-streaming` output to the Cloud docs.
**Revert change to local playbook before merging**
[`snowflake_streaming` output](https://deploy-preview-118--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/outputs/snowflake_streaming/)
[DOC-734]: https://redpandadata.atlassian.net/browse/DOC-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-734 Adds `snowflake_streaming` output to the Cloud docs

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/inputs/spicedb_watch.adoc
Resolves: [DOC-734](https://redpandadata.atlassian.net/browse/DOC-734)
Review deadline: 15 November
[`spicedb_watch` input](https://deploy-preview-120--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/spicedb_watch/)
[DOC-734]: https://redpandadata.atlassian.net/browse/DOC-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-734 Add spicedb_watch input to Cloud docs

modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc
TLS is enabled by default so we've switched most of our example commands to include it. Whenever I follow this document I always forget to include it, if I'm forgetting possibly others are too.
https://deploy-preview-142--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/remote-read-replicas/#create-remote-read-replica
=> Add --tls-enabled to the remote read replicas topic command

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/consume-data/follower-fetching.adoc, modules/develop/pages/produce-data/configure-producers.adoc, modules/develop/pages/produce-data/leader-pinning.adoc, modules/get-started/pages/whats-new-cloud.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-712
Review deadline: Nov 25
[What's New in Redpanda Cloud](https://deploy-preview-131--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/)
[Leader pinning in Cloud docs](https://deploy-preview-131--rp-cloud.netlify.app/redpanda-cloud/develop/produce-data/leader-pinning/)
[Leader pinning in Self Managed docs](https://deploy-preview-131--rp-cloud.netlify.app/current/develop/produce-data/leader-pinning//)
=> DOC-712 Cloud leader pinning

modules/get-started/pages/cloud-overview.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-754
Review deadline: Nov 27
[Redpanda Cloud vs Self-Managed feature compatibility](https://deploy-preview-122--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#redpanda-cloud-vs-self-managed-feature-compatibility)
=> Update SM vs Cloud features compatibility

modules/networking/pages/aws-privatelink.adoc, modules/networking/pages/azure-private-link.adoc, modules/networking/pages/configure-private-service-connect-in-cloud-ui.adoc, modules/networking/pages/configure-privatelink-in-cloud-ui.adoc, modules/networking/pages/gcp-private-service-connect.adoc
This adds a tip to the AWS Private Link, Azure PrivateLink, and GCP Private Service Connect pages to alert users that as soon as the private service is available on your VPC, all communication on existing Redpanda public ports is interrupted & to have apps running in your VPC ready to start using the corresponding private ports.
Resolves https://redpandadata.atlassian.net/browse/DOC-662
Review deadline: Dec 12
- [AWS PrivateLink API](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/aws-privatelink/)
- [Azure Private Link API](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/azure-private-link/)
- [GCP API](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/gcp-private-service-connect/)
- [AWS PrivateLink …
=> DOC-662 interrupted communication after private networking

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/processors/benchmark.adoc
Resolves [DOC-849](https://redpandadata.atlassian.net/browse/DOC-849)
Review deadline: 11th December
[`benchmark` processor](https://deploy-preview-151--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/processors/benchmark/)
[DOC-849]: https://redpandadata.atlassian.net/browse/DOC-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-849 Add benchmark processor to Cloud docs

modules/get-started/pages/whats-new-cloud.adoc, modules/networking/pages/aws-privatelink.adoc, modules/networking/pages/configure-privatelink-in-cloud-ui.adoc
This removes the note about needing Support to enable AWS PrivateLink. It also reorders the steps for configuring PrivateLink in the UI. 
Resolves https://redpandadata.atlassian.net/browse/DOC-895, https://redpandadata.atlassian.net/browse/DOC-896
Review deadline: Jan 7
- [Configure AWS PrivateLink in the Cloud UI](https://deploy-preview-163--rp-cloud.netlify.app/redpanda-cloud/networking/configure-privatelink-in-cloud-ui/)
- [Configure AWS PrivateLink with the Cloud API](https://deploy-preview-163--rp-cloud.netlify.app/redpanda-cloud/networking/aws-privatelink/)
=> DOC-895 remove AWS privatelink feature flag

modules/security/partials/iam-policies.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-818
Review deadline: Dec 12
[AWS IAM Policies](https://deploy-preview-155--rp-cloud.netlify.app/redpanda-cloud/security/authorization/cloud-iam-policies/)
[Azure IAM Policies](https://deploy-preview-155--rp-cloud.netlify.app/redpanda-cloud/security/authorization/cloud-iam-policies-azure/)
[GCP IAM Policies](https://deploy-preview-155--rp-cloud.netlify.app/redpanda-cloud/security/authorization/cloud-iam-policies-gcp/)
=> DOC-818 clarify cloud IAM policy

package-lock.json, package.json
Review deadline: 10 Jan
Using `latest` is considered bad practice because we could auto-update to a version with breaking changes.
This PR specifies a range that allows upgrades to new minor and patch versions.
=> Specify a valid semver range for extensions package

modules/develop/pages/managed-connectors/index.adoc, modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc, modules/get-started/pages/cluster-types/dedicated/create-dedicated-cloud-cluster.adoc, modules/shared/partials/kafka-connect.adoc
- This adds a section to the Redpanda Cloud Overview about Redpanda Connect and Kafka Connect, explaining that it's enabled with a running node for it on AWS and GCP + link to how to enable on Azure. 
- This also adds a link to Enable Kafka Connect on Azure on the page for creating Dedicated clusters. 
Resolves https://redpandadata.atlassian.net/browse/DOC-919, https://redpandadata.atlassian.net/browse/DOC-452
Review deadline: Jan 10
- [Redpanda Cloud Overview - Redpanda Connect and Kafka Connect](https://deploy-preview-167--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#redpanda-connect-and-kafka-connect)
- [Create a Dedicated Cluster](https://deploy-preview-167--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/dedicated/create-dedicated-cloud-cluster/)
- …
=> DOC-919 enable Kafka Connect in Azure Dedicated

modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc
This PR accompanies https://github.com/redpanda-data/docs/pull/942 to clarify cross region support for RRR/tiered storage.
Review deadline: 14 Jan
=> Cross region support for RRR

modules/develop/pages/managed-connectors/index.adoc
Resolves [Doc-194](https://redpandadata.atlassian.net/browse/DOC-194)
Review deadline: **Monday, January 13**
[Kafka Connect 1st paragraph](https://deploy-preview-171--rp-cloud.netlify.app/redpanda-cloud/develop/managed-connectors/)
=> Doc-194 Clarification about who is responsible for certain Kafka Connect tasks

modules/reference/partials/tiers.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-951
add eu-west-3 region for AWS Dedicated
available in UI:
Review deadline: Jan 15
[Dedicated regions](https://deploy-preview-174--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/dedicated-tiers/?tab=tabs-1-amazon-web-services-aws#dedicated-supported-regions)
=> DOC-951 Doc Dedicated region AWS eu-west-3

modules/get-started/pages/cloud-overview.adoc
updates Serverless limits, per discussion [here](https://redpandadata.slack.com/archives/C088LB383B9/p1737033993145649)
Resolves https://redpandadata.atlassian.net/browse/DOC-956
https://deploy-preview-176--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/
=> DOC-956 update Serverless limits

modules/get-started/pages/cloud-overview.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-19
[Redpanda Cloud Overview - BYOC](https://deploy-preview-175--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#bring-your-own-cloud-byoc)
=> DOC-19 not using BYOC to manage other workloads

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/serverless-pro.adoc, modules/get-started/pages/cluster-types/serverless.adoc
This updates the standard and pro limits on the deployment pages
Resolves https://redpandadata.atlassian.net/browse/DOC-957
[Serverless Standard](https://deploy-preview-178--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless/)
[Serverless Pro](https://deploy-preview-178--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless-pro/)
=> Doc 956 update serverless limits

modules/reference/partials/tiers.adoc
Adds europe-west3 region for GCP on Dedicated
Resolves https://redpandadata.atlassian.net/browse/DOC-954
Review deadline: Jan 21
https://deploy-preview-180--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/dedicated-tiers/#dedicated-supported-regions
=> DOC-954 enable europe-west3 for GCP

modules/billing/pages/billing.adoc, modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/serverless-pro.adoc, modules/get-started/pages/cluster-types/serverless.adoc
To match code, this updates topic limit for Serverless Pro from 200 to 300. 
Resolves https://redpandadata.atlassian.net/browse/DOC-974
Review deadline: Jan 24
https://deploy-preview-183--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless-pro/#serverless-pro-usage-limits
=> DOC-974 updated topic limit in Serverless Pro

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
When creating an AWS BYOVPC cluster the customer typically has 1 of 2 scenarios:
1) They already have a VPC created that they want to use 2) They are using our terraform code to create a VPC following our specifications
Never would they want to create the VPC using an `aws ec2 create-vpc` command as specified here. The command even includes a hard-coded profile name that is only valid internal to Redpanda. We should not expose this profile name outside of Redpanda.
=> Remove reference to `aws ec2 create-vpc`

local-antora-playbook.yml, package-lock.json, package.json
For details, see https://redpandadata.atlassian.net/wiki/spaces/DOC/pages/1051328557/Mermaid+diagrams
=> Add mermaid diagram support for local builds

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
This puts the "customer_managed_resources" block back in + adds that the AWS CIDR must be set to /24.
Resolves https://redpandadata.atlassian.net/browse/DOC-984
Create BYOVPC on AWS:
- [Create environment variables](https://deploy-preview-189--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/vpc-byo-aws/#set-environment-variables)
- [Create cluster](https://deploy-preview-189--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/vpc-byo-aws/#create-cluster)
=> DOC-984 update BYOVPC on AWS steps

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc
This adds the beta badge for BYOVPC for Azure + updates the LA/beta list in the overview. 
Resolves https://redpandadata.atlassian.net/browse/DOC-1002
Review deadline: Jan 31
[Overview - features in LA/beta](https://deploy-preview-194--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#features-in-limited-availability)
[BYOVPC for Azure](https://deploy-preview-194--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/azure/vnet-azure/)
=> DOC-1002 mark BYOVPC Azure as beta

modules/get-started/pages/cloud-overview.adoc
This removes `rpk security user` from the list of commands not supported in Cloud, since they are now supported. (The commands already appeared in the rpk reference in Cloud, since they were previously supported in Serverless clusters.)
Resolves https://redpandadata.atlassian.net/browse/DOC-894
[Cloud vs Self-Managed feature compatibility](https://deploy-preview-186--rp-cloud.netlify.app/redpanda-cloud/get-started/cloud-overview/#redpanda-cloud-vs-self-managed-feature-compatibility)
=> DOC-894 allow `rpk security user` in Cloud

modules/develop/pages/connect/components/outputs/snowflake_streaming.adoc
Resolves [DOC-972](https://redpandadata.atlassian.net/browse/DOC-972)
Review deadline: 4th February
[`snowflake_streaming` output](https://deploy-preview-195--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/outputs/snowflake_streaming/)
[DOC-972]: https://redpandadata.atlassian.net/browse/DOC-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-972 Remove beta attribute from snowflake_streaming output

modules/get-started/partials/no-access.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-1015
Review deadline: Feb 5
The note on all pages has been updated to: https://deploy-preview-198--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/create-byoc-cluster-aws/#next-steps
=> DOC-1015 clarify K8s access

modules/develop/pages/connect/about.adoc, modules/develop/partials/availability-message.adoc, modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/byoc/aws/index.adoc, modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc, modules/get-started/pages/cluster-types/byoc/azure/index.adoc, modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc, modules/get-started/pages/cluster-types/byoc/gcp/index.adoc, modules/get-started/pages/cluster-types/byoc/gcp/vpc-byo-gcp.adoc, modules/get-started/pages/cluster-types/byoc/index.adoc, modules/shared/partials/feature-flag-rpcn.adoc
This adds clarifications about BYOVPC and Redpanda Connect availability. 
Resolves https://redpandadata.atlassian.net/browse/DOC-1007, https://redpandadata.atlassian.net/browse/DOC-1009
Review deadline: Feb 6
- [RPCN in Redpanda Cloud](https://deploy-preview-196--rp-cloud.netlify.app/redpanda-cloud/develop/connect/about/) (also in [RPCN Quickstart](https://deploy-preview-196--rp-cloud.netlify.app/redpanda-cloud/develop/connect/connect-quickstart/))
- BYOVPC on [AWS](https://deploy-preview-196--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/vpc-byo-aws/), [Azure](https://deploy-preview-196--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/azure/vnet-azure/), [GCP](https://deploy-preview-196--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-ty …
=> DOC-1007 clarify BYOVPC limitations

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-1020
Review deadline: Feb 7
https://deploy-preview-202--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/vpc-byo-aws/#prerequisites
=> DOC-1020 link artifact in BYOVPC for AWS

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/inputs/mysql_cdc.adoc
Resolves [DOC-820](https://redpandadata.atlassian.net/browse/DOC-820)
Review deadline: 19th February
[`mysql_cdc` input](https://deploy-preview-203--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/mysql_cdc/)
[DOC-820]: https://redpandadata.atlassian.net/browse/DOC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-820 Add `mysql_cdc` connector to Cloud docs

modules/manage/pages/api/cloud-api-authentication.adoc, modules/manage/pages/api/cloud-api-quickstart.adoc
Review deadline: 24 Feb
This pull request includes updates to the documentation for creating and using service accounts in the Redpanda Cloud UI. The changes clarify the steps and update the UI references to reflect the current interface.
Documentation updates:
* [`modules/manage/pages/api/cloud-api-authentication.adoc`](diffhunk://#diff-41532e4093374254341a9d4160f5f37e109fc0f039f55b85f05fe492391fb44aL20-R34): Updated instructions for creating a service account and obtaining the client ID and secret, including a new example of making a POST request to get an API token.
* [`modules/manage/pages/api/cloud-api-quickstart.adoc`](diffhunk://#diff-16a138b2faf55645dfb47e7dcfdccc924f15c254f941eeb7d6 …
=> Update authN instructions with new UI

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/serverless-pro.adoc, modules/get-started/pages/whats-new-cloud.adoc
This pull request increases the throughput and partition limits for Serverless Pro clusters.
Changes to throughput and partition limits:
* [`modules/get-started/pages/cloud-overview.adoc`](diffhunk://#diff-10401c3a5fb2293775dd5cfed082eea9183cddd81dbd8664ab04e35c1f407b0bL21-R23): Increased the max write throughput from 10 MB/s to 100 MB/s, the max read throughput from 30 MB/s to 300 MB/s, and the partition limit from 500 to 5000 for Serverless Pro clusters.
* [`modules/get-started/pages/cluster-types/serverless-pro.adoc`](diffhunk://#diff-615b10a951b12e2feada2739516a97073df5038ec68aa04efa46a26a43aaefebL16-R19): Updated the ingress limit from 10 MBps to 100 MBps, the egress limit from 30 MBps to 300 MBps, and the partition limit from 500 to 5000 for Serverless Pro clusters.
Resolves …
=> DOC-1036 new Serverless Pro limits

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/byoc/aws/create-byoc-cluster-aws.adoc, modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc, modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc, modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc, modules/get-started/pages/cluster-types/byoc/gcp/create-byoc-cluster-gcp.adoc, modules/get-started/pages/cluster-types/byoc/gcp/vpc-byo-gcp.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/networking/pages/configure-private-service-connect-in-cloud-ui.adoc, modules/networking/pages/gcp-private-service-connect.adoc, modules/networking/partials/private-links-api-access-token.adoc
This pull request adds new permissions and firewall rules. Here are the most important changes:
* Added new permissions to the `redpanda-agent.role` and `redpanda-gke.role` in `modules/get-started/pages/cluster-types/byoc/gcp/vpc-byo-gcp.adoc`. [[1]](diffhunk://#diff-73505660c362559206baf921b88084a157f6730dc11b6895f3477170b71047b9R179) [[2]](diffhunk://#diff-73505660c362559206baf921b88084a157f6730dc11b6895f3477170b71047b9R212-R247) [[3]](diffhunk://#diff-73505660c362559206baf921b88084a157f6730dc11b6895f3477170b71047b9R442-R449)
* Added commands for creating firewall rules in `modules/networking/pages/configure-private-service-connect-in-cloud-ui.adoc` and `modules/networking/pages/gcp-private-service-connect.adoc`. [[1]](diffhunk://#diff-2bfa9933fae9ea3a4c66b82b452f77f3f5828891997345a99631 …
=> DOC-1014 update BYOVPC and PSC

local-antora-playbook.yml
Reverts local-antora-playbook.yml
Resolves https://redpandadata.atlassian.net/browse/DOC-1060
=> DOC-1060 fix local-antora-playbook.yml branches

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/networking/pages/configure-private-service-connect-in-cloud-ui.adoc, modules/networking/pages/gcp-private-service-connect.adoc
This pull request removes GCP Private Service Connect from the list of limited availability features and removes the feature flag admonition from PSC doc files.
Changes to documentation:
* [`modules/get-started/pages/cloud-overview.adoc`](diffhunk://#diff-10401c3a5fb2293775dd5cfed082eea9183cddd81dbd8664ab04e35c1f407b0bL317): Removed GCP Private Service Connect from the list of features in limited availability.
* [`modules/networking/pages/configure-private-service-connect-in-cloud-ui.adoc`](diffhunk://#diff-2bfa9933fae9ea3a4c66b82b452f77f3f5828891997345a99631d5827d490e56L5-L6): Removed the feature flag include statement.
* [`modules/networking/pages/gcp-private-service-connect.adoc`](diffhunk://#diff-f3fed6dbc7157a74820c0be4c8752d6a386697a878f850663c396f2c329f0280L5-L6): Removed the …
=> DOC-1064 remove LA for PSC

modules/shared/partials/feature-flag-rpcn.adoc
This pull request includes a small change to the `modules/shared/partials/feature-flag-rpcn.adoc` file. The change updates the contact link for unlocking the BYOVPC feature from Redpanda Support to Redpanda Sales.
* [`modules/shared/partials/feature-flag-rpcn.adoc`](diffhunk://#diff-c4260561e4716470d26f9108a713b6b990906a7c753fe824ea62f0d72da0c1fcL4-R4): Updated the contact link for unlocking the BYOVPC feature to point to Redpanda Sales.
Resolves https://redpandadata.atlassian.net/browse/DOC-1067
Review deadline: Feb 27
BYOVPC on [AWS](https://deploy-preview-218--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/vpc-byo-aws/), [Azure](https://deploy-preview-218--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/azure/vnet-azure/), …
=> DOC-1067 Direct BYOVPC to sales instead of support

modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc
The word 'account' is associated with AWS and not GCP. This may have caused confusion.
https://deploy-preview-223--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/remote-read-replicas/
=> Clarify AWS/GCP account/project requires for remote read replicas

modules/get-started/pages/whats-new-cloud.adoc, modules/reference/partials/tiers.adoc
This add a new supported region for BYOC clusters on GCP.
Documentation updates:
* [`modules/get-started/pages/whats-new-cloud.adoc`](diffhunk://#diff-825e3d404929927e196111eaa92a310ee71d39aa9310418f56a55099a3a3f7c3R10-R15): Added an entry for March 2025 mentioning the support for the GPC europe-southwest1 region (Madrid) for BYOC clusters.
* [`modules/reference/partials/tiers.adoc`](diffhunk://#diff-4a284041e150b37b311c93863e20d3d09c6fa62c1c3a3832c72f9c3469a6d867R45): Updated the list of supported regions to include europe-southwest1.
Resolves https://redpandadata.atlassian.net/browse/DOC-1082
https://deploy-preview-225--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/
=> DOC-1082 add BYOC GCP europe-southwest1

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/inputs/mongodb_cdc.adoc
Resolves [DOC-514](https://redpandadata.atlassian.net/browse/DOC-514)
Review deadline: 7th March
[mongodb_cdc](https://deploy-preview-227--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/mongodb_cdc/)
[DOC-514]: https://redpandadata.atlassian.net/browse/DOC-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-514 Add mongodb_cdc to cloud-docs

modules/ROOT/nav.adoc, modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/manage/pages/maintenance.adoc
* Creates a new file `modules/manage/pages/maintenance.adoc` with info on how Redpanda Cloud handles upgrades and maintenance, including scheduling maintenance windows and the default maintenance cycle.
* Moves the maintenance windows section from `modules/get-started/pages/cloud-overview.adoc` into the new maintenance page.
* Adds a new reference to the maintenance documentation in the navigation file `modules/ROOT/nav.adoc`.
* Adds a link to the new maintenance documentation in the "Next steps" section of `modules/get-started/pages/cloud-overview.adoc`.
* Updates the link to schedule a maintenance window in `modules/get-started/pages/whats-new-cloud.adoc` to point to the new maintenance documentation.
Resolves https://redpandadata.atlassian.net/browse/DOC-821
Review deadline: Feb 28 …
=> DOC-821 create upgrades page for Cloud

modules/get-started/pages/whats-new-cloud.adoc, modules/networking/pages/configure-private-service-connect-in-cloud-ui.adoc, modules/networking/pages/gcp-private-service-connect.adoc, modules/security/partials/iam-policies.adoc
This updates the GCP IAM policies with PSC v2. It adds permissions for forwarding rules, instances, networks, region backend services, and service attachments; and removes a permission for retrieving specified networks. It also adds deprecation notices for the original PSC service. 
Updates to permissions:
* Added multiple permissions related to `compute.forwardingRules`, including create, delete, get, and update operations.
* Added `compute.instances.use` permission.
* Removed `compute.networks.get` permission.
* Added permissions for `compute.regionBackendServices` and `compute.regionNetworkEndpointGroups`, including create, delete, get, and use operations.
* Added permissions for `compute.serviceAttachments`, including create, delete, get, list, and update operations.
* Added …
=> DOC-1088 update GCP IAM policies for PSC

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/outputs/elasticsearch_v8.adoc
Resolves [DOC-1051](https://redpandadata.atlassian.net/browse/DOC-1051)
Review deadline: 5th March
[`elasticsearch_v8` output](https://deploy-preview-224--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/outputs/elasticsearch_v8/)
[DOC-1051]: https://redpandadata.atlassian.net/browse/DOC-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1051 Add elasticsearch_v8 to cloud docs

modules/get-started/pages/whats-new-cloud.adoc, modules/networking/pages/configure-private-service-connect-in-cloud-ui.adoc, modules/networking/pages/gcp-private-service-connect.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-1110
=> DOC-1110 call out PSC deprecation

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
Some of these fields should be surrounded by quotes, as in the below create cluster example as well.
Removed an extra trailing comma that is invalid.
=> Fix minor typos in AWS BYOVPC documentation

modules/develop/pages/connect/components/inputs/mongodb_cdc.adoc, modules/develop/pages/connect/components/inputs/mysql_cdc.adoc
Resolves [DOC-1128](https://redpandadata.atlassian.net/browse/DOC-1128)
Review deadline: 18 March
[`mongodb_cdc` input](https://deploy-preview-235--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/mongodb_cdc/)
[`mysql_cdc` input](https://deploy-preview-235--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/mysql_cdc/)
[DOC-1128]: https://redpandadata.atlassian.net/browse/DOC-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1128 Remove beta flags mongodb_cdc and mysql_cdc cloud docs

modules/develop/pages/connect/components/inputs/postgres_cdc.adoc
Resolves DOC-1130
Review deadline: 19 March
This pull request removes the beta status from the `postgres_cdc` page.
[`postgres_cdc` input](https://deploy-preview-236--rp-cloud.netlify.app/redpanda-cloud/develop/connect/components/inputs/postgres_cdc/)
=> DOC-1130 Remove beta flag from postgres_cdc cloud docs

modules/develop/pages/connect/about.adoc, modules/develop/pages/connect/configuration/resource-management.adoc, modules/develop/pages/connect/configuration/secret-management.adoc, modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc, modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc, modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc, modules/get-started/pages/cluster-types/byoc/remote-read-replicas.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/manage/pages/api/cloud-api-authentication.adoc, modules/manage/pages/api/cloud-api-errors.adoc, modules/manage/pages/api/cloud-api-overview.adoc, modules/manage/pages/api/cloud-api-quickstart.adoc, modules/manage/pages/api/cloud-byoc-controlplane-api.adoc, modules/manage/pages/api/cloud-dataplane-api.adoc, modules/manage/pages/api/cloud-dedicated-controlplane-api.adoc, modules/manage/pages/api/cloud-serverless-controlplane-api.adoc, modules/manage/pages/api/controlplane/index.adoc, modules/manage/pages/api/index.adoc, modules/manage/partials/controlplane-api.adoc, modules/networking/pages/aws-privatelink.adoc, modules/networking/pages/azure-private-link.adoc, modules/networking/pages/gcp-private-service-connect.adoc, modules/security/pages/cloud-authentication.adoc
.## Description
This pull request adds new documentation for managing RBAC (Role-Based Access Control) in the control plane. The changes include instructions for listing role bindings, getting role bindings, getting user details, creating role bindings, and creating service accounts.
New RBAC management documentation:
* Added a section on managing RBAC configurations, including assigning roles to users and service accounts.
* Provided examples of API requests for listing role bindings, getting role bindings, and getting user details.
Review deadline: 27 Feb 2025
[Use Control Plane API with BYOC > Manage RBAC](https://deploy-preview-211--rp-cloud.netlify.app/redpanda-cloud/manage/api/cloud-by …
=> Use Cloud API for RBAC

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/serverless.adoc, modules/get-started/partials/get-started-serverless.adoc
This pull request adds a link to the Serverless trial, extracts Serverless sign-up details into a partial file for reuse, and adds similar tabs for Dedicated cluster sign-up options.
Improvements to Serverless sign-up information:
* [`modules/get-started/pages/cloud-overview.adoc`](diffhunk://#diff-10401c3a5fb2293775dd5cfed082eea9183cddd81dbd8664ab04e35c1f407b0bL41-R45): Removed detailed Serverless sign-up instructions and replaced them with a reference to a partial file.
* [`modules/get-started/pages/cluster-types/serverless.adoc`](diffhunk://#diff-b9ada45e986054dd3c87aefcc43f539e63aff7eb5e016458549138ad6445ac73L32-R32): Replaced detailed Serverless sign-up instructions with an inclusion of the partial file containing the sign-up details.
* …
=> DOC-1148 add Serverless trial link

modules/networking/pages/aws-privatelink.adoc, modules/networking/pages/azure-private-link.adoc, modules/networking/pages/configure-privatelink-in-cloud-ui.adoc
This pull request includes documentation updates for optimizing Kafka client configurations when using PrivateLink services in AWS and Azure. The changes provide additional tips for setting the `connections.max.idle.ms` parameter to improve client stability.
Documentation updates:
* [`modules/networking/pages/configure-privatelink-in-cloud-ui.adoc`](diffhunk://#diff-c251c8951879bdb57e77fa5fda3a50ec9e7b4f77790279dd23e9bbe8f96d5284R20-R21): Added a tip to set `connections.max.idle.ms` to less than 350 seconds for Kafka clients.
* [`modules/networking/pages/aws-privatelink.adoc`](diffhunk://#diff-66ea720430f41f22a8c57e10687a5532decb00a5108ec6b715e1e0fc9b4978acR27-R28): Added a tip to set `connections.max.idle.ms` to less than 350 seconds for Kafka clients.
* …
=> DOC-774 doc best practices with private link

modules/get-started/pages/cluster-types/byoc/aws/create-byoc-cluster-aws.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-1183
https://deploy-preview-252--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/byoc/aws/create-byoc-cluster-aws/#prerequisites
=> DOC-1183 fix formatting

modules/get-started/pages/cluster-types/serverless.adoc
This pull request includes changes to the `modules/get-started/pages/cluster-types/serverless.adoc` file:
* Updated the description for private networking to specify "VPC peering or AWS PrivateLink" instead of a general statement.
* Separated the feature of multiple availability zones (AZs) into its own bullet point for clarity.
Resolves [https://github.com/redpanda-data/documentation-private/issues/<add-your-issue-number-here>](https://redpandadata.atlassian.net/browse/DOC-1224)
https://deploy-preview-256--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless/#supported-features
=> DOC-1224 specify PL and peering not supported in Serverless

modules/ROOT/nav.adoc, modules/develop/pages/data-transforms/build.adoc, modules/develop/pages/data-transforms/how-transforms-work.adoc, modules/develop/pages/data-transforms/run-transforms.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/manage/pages/audit-logging.adoc, modules/manage/pages/cluster-maintenance/config-cluster.adoc
This pull request includes several updates to the documentation for data transforms and audit logging. The most important changes include the removal of the Data Transforms Quickstart section, the addition of support notes for BYOC and Dedicated clusters, and the addition of a page alias.
Single-sourcing of updated text in the `docs` repo is done in https://github.com/redpanda-data/docs/pull/1079.
Documentation updates:
* [`modules/ROOT/nav.adoc`](diffhunk://#diff-5daf5a85fd51578ad9fc545388bf62176bcea32094ee97b5e30c2eea044e4193L363): Removed the link to the Data Transforms Quickstart section.
* [`modules/develop/pages/data-transforms/how-transforms-work.adoc`](diffhunk://#diff-3e86940a8aa1d700365135b8974a6159439731807a9a0367d3b907f3c721ea22R4): Added a page alias for the removed Data …
=> DOC-1236 remove wasm quickstart from cloud

modules/billing/pages/billing.adoc
This pull request introduces a clarification to the billing documentation for Serverless clusters. The change specifies that uptime is not charged when both partitions and storage are zero.
* [`modules/billing/pages/billing.adoc`](diffhunk://#diff-e1d4caca64cf7059e6701065a142427ca0abb3f361c8346f58ad114b396b5fd5R21-R22): Added a note clarifying that uptime charges are waived if `partitions = 0` and `storage = 0`.
Resolves https://redpandadata.atlassian.net/browse/DOC-1277
Review deadline: April 29
[Serverless metrics](https://deploy-preview-277--rp-cloud.netlify.app/redpanda-cloud/billing/billing/#serverless-metrics)
=> DOC-1277 Serverless scale to zero

modules/manage/pages/rpk/config-rpk-profile.adoc, modules/reference/pages/rpk/rpk-help.adoc, modules/reference/pages/rpk/rpk-version.adoc, modules/reference/pages/rpk/rpk-x-options.adoc
Resolves https://redpandadata.atlassian.net/browse/DOC-1339
This pull request updates several `rpk` documentation files to use a specific tagged section for content inclusion. The changes ensure consistency and enable single-sourcing of documentation across files.
Documentation updates for single-sourcing:
* [`modules/reference/pages/rpk/rpk-help.adoc`](diffhunk://#diff-c04ec961a4f928339a256659fd23791a5904a9364f3894f78c858c42c9764c0aL3-R3): Updated the `include` directive to use the `tag=single-source` parameter for content inclusion.
* [`modules/reference/pages/rpk/rpk-version.adoc`](diffhunk://#diff-b7d57fffc2cc499493ba0442601caa03646877d10a5fdd9d861bc229a4e9284aL3-R3): Modified the `include` directive to reference the `tag=single-source` parameter for better content management.
* …
=> DOC-1339 fix single sourcing

modules/get-started/pages/whats-new-cloud.adoc, modules/reference/partials/tiers.adoc
This pull request introduces updates to the documentation for Redpanda Cloud, specifically adding support for a new GCP region. The changes ensure that the feature is reflected in both the "What's New" section and the list of supported regions.
* [`modules/get-started/pages/whats-new-cloud.adoc`](diffhunk://#diff-825e3d404929927e196111eaa92a310ee71d39aa9310418f56a55099a3a3f7c3R10-R15): Added an entry for May 2025 announcing support for the `us-west2` (Los Angeles) region for BYOC clusters on GCP.
* [`modules/reference/partials/tiers.adoc`](diffhunk://#diff-4a284041e150b37b311c93863e20d3d09c6fa62c1c3a3832c72f9c3469a6d867R58): Updated the list of supported GCP regions to include `us-west2`.
Resolves https://redpandadata.atlassian.net/browse/DOC-1213
[What's …
=> DOC-1213 Document feature BYOC in GCP us-west2

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
Ensures that our docs uses default for Redpanda Connect on BYOVPC AWS is opt out via docs., with some information on how to disable it explicitly.
=> Update vpc-byo-aws.adoc - Connect by default

modules/get-started/pages/whats-new-cloud.adoc, modules/security/pages/cloud-authentication.adoc
New doc on simultaneously enabling mTLS and SASL for Kafka API, HTTP Proxy, and Schema Registry on GCP clusters.
Also adds a new matrix to more easily convey what auth protocols are available for which Redpanda services based on cloud provider.
Review deadline: 9 May
[Enable mTLS + SASL authentication](https://deploy-preview-279--rp-cloud.netlify.app/redpanda-cloud/security/cloud-authentication/#mtls-sasl)
[What's New in Redpanda Cloud
](https://deploy-preview-279--rp-cloud.netlify.app/redpanda-cloud/get-started/whats-new-cloud/#april-2025)
=> Enable mTLS and SASL (GCP)

modules/get-started/pages/cluster-types/byoc/gcp/vpc-byo-gcp.adoc
=> Update vpc-byo-gcp.adoc - missing comma in BYOVPC role

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/processors/google_drive_list_labels.adoc
Resolves: [DOC-1311](https://redpandadata.atlassian.net/browse/DOC-1311)
Review deadline: 14 May
This pull request introduces a new processor, `google_drive_list_labels`, to the documentation and updates the relevant configuration and navigation files to include it. The most important changes are grouped below by theme.
* Added a new page for the `google_drive_list_labels` processor in `modules/develop/pages/connect/components/processors/google_drive_list_labels.adoc`. This includes a page alias and content sourced from a single source file.
* Updated the `branches` value in `local-antora-playbook.yml` for the `rp-connect-docs` repository to point to the `DOC-1311_Add_google_drive_list_labels_processor` branch.
* Added a navigation entry for the new `google_drive_list_labels` processor in …
=> DOC-1311 Add google_drive_list_labels processor to cloud

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/develop/pages/connect/components/processors/google_drive_download.adoc
Resolves [DOC-1310](https://redpandadata.atlassian.net/browse/DOC-1310)
Review deadline: 14 May
This pull request introduces updates to the documentation for Redpanda Connect, specifically adding support for the new Google Drive Download processor. The changes include updating the branch for the `rp-connect-docs` repository, adding navigation for the new processor, and including its documentation.
* **Branch Update for Documentation Source**:
- Updated the branch in `local-antora-playbook.yml` for the `rp-connect-docs` repository to `DOC-1310_Add_google_drive_download_processor` to pull the relevant changes for the new processor.
* **Navigation Update**:
- Added a navigation entry in `modules/ROOT/nav.adoc` for the new Google Drive Download processor documentation.
* **Documentation …
=> DOC-1310 Add google_drive_download processor to Cloud

modules/networking/pages/gcp-private-service-connect.adoc
Still testing BYOC, and will need to test BYOVPC as well. In general, we should try to use curly braces around SHELL variables as described here: https://stackoverflow.com/questions/8748831/when-do-we-need-curly-braces-around-shell-variables. Removed one env variable in the subnet configure step, as the accept list is in the next step.
=> Update gcp-private-service-connect.adoc - Add more steps for BYOC

modules/reference/partials/tiers.adoc
This pull request updates documentation in the `modules/reference/partials/tiers.adoc` file to clarify partition count limits for Redpanda clusters. The changes specify that the limits are based on Redpanda version 25.1.
* Updated partition count descriptions to specify that limits are based on Redpanda version 25.1 in the usage tier details for BYOC clusters.
* Updated partition count descriptions to specify that limits are based on Redpanda version 25.1 in the usage tier details for Dedicated clusters.
Resolves https://redpandadata.atlassian.net/browse/DOC-1278
[BYOC usage tiers](https://deploy-preview-300--rp-cloud.netlify.app/redpanda-cloud/reference/tiers/byoc-tiers/#byoc-usage-tiers)
[Dedicate usage tiers](https://deploy-preview-300--rp-cloud.netlify.app/redpanda-clo …
=> DOC-1278 add clarification note for partition limits

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/manage/pages/iceberg/redpanda-topics-iceberg-snowflake-catalog.adoc
This pull request introduces updates to the documentation to include a new feature for querying Iceberg topics with Snowflake. The most important changes involve adding a new branch to the Antora playbook, updating the navigation structure, and creating a new documentation page for this feature.
See related PR: https://github.com/redpanda-data/docs/pull/1131
* **Antora playbook update**: Added the branch `'DOC-1389-Iceberg-on-Cloud-Single-source-Snowflake-doc'` to the `content:` section in `local-antora-playbook.yml` to include the new documentation source.
* **Navigation structure update**: Added a new navigation entry in `modules/ROOT/nav.adoc` for the page `redpanda-topics-iceberg-snowflake-catalog.adoc`, titled "Query Iceberg Topics with Snowflake."
* **New documentation page**: …
=> Add Iceberg Snowflake doc to Cloud

modules/get-started/pages/cluster-types/byoc/aws/vpc-byo-aws.adoc
If no internet gateway is provided (the default setting), then the creation of the BYOVPC cluster will fail. Related to change made in the `cloud-examples` repo: https://github.com/redpanda-data/cloud-examples/pull/50
=> Update vpc-byo-aws.adoc - add create_internet_gateway flag

modules/get-started/pages/create-topic.adoc
This pull request updates the `create-topic.adoc` file to improve clarity and include additional details about Redpanda features. The most notable change is the addition of information about Tiered Storage being enabled by default in Redpanda Cloud.
Documentation improvements:
* [`modules/get-started/pages/create-topic.adoc`](diffhunk://#diff-06778b53581a732b5e0962d5126eaa6218bad56802d340dc828ae179fb2cc9a5L7-R16): Enhanced the description of topics to emphasize their role in organizing events and added a note about Tiered Storage being enabled and configurable by default in Redpanda Cloud.
Resolves https://redpandadata.atlassian.net/browse/DOC-8
https://deploy-preview-307--rp-cloud.netlify.app/redpanda-cloud/get-started/create-topic/
=> DOC-8 clarity how to enable tiered storage in Cloud

modules/get-started/pages/whats-new-cloud.adoc, modules/manage/pages/api/cloud-api-overview.adoc, modules/manage/pages/maintenance.adoc
This pull request focuses on documenting the deprecation of several Cloud API beta versions and updating relevant sections across multiple documentation files. The most important changes involve adding notices about the deprecated API versions and linking to the deprecation policy for further details.
* [`modules/get-started/pages/whats-new-cloud.adoc`](diffhunk://#diff-825e3d404929927e196111eaa92a310ee71d39aa9310418f56a55099a3a3f7c3R12-R15): Added a new section under "May 2025" announcing the deprecation of Cloud Control Plane API versions `v1beta1` and `v1beta2`, and Data Plane API versions `v1alpha1` and `v1alpha2`. These versions are marked for future removal and are not recommended for use.
* [`modules/manage/pages/api/cloud-api-overview.adoc`](diffhunk://#diff-a925e672ba8c10f79e29531 …
=> Add deprecation notice for Cloud API

modules/get-started/pages/whats-new-cloud.adoc, modules/manage/pages/maintenance.adoc
This pull request updates documentation to reflect the deprecation and migration of the Serverless Standard platform and associated clusters. It also clarifies the deprecation timeline for related products.
* [`modules/get-started/pages/whats-new-cloud.adoc`](diffhunk://#diff-825e3d404929927e196111eaa92a310ee71d39aa9310418f56a55099a3a3f7c3R12-R17): Added details about the deprecation of Serverless Standard, including migration of clusters to the new Serverless platform with higher usage limits, 99.9% SLA, and additional regions. Migration will occur on August 31, 2025, with a retirement date of August 30, 2025.
* [`modules/manage/pages/maintenance.adoc`](diffhunk://#diff-531001571c634f60e334f3906cd4257a926abe42fe2c54fd92e3f90f2e1209cfL127-R132): Updated the deprecation timeline to include …
=> DOC-1357 add desupported date for Serverless Standard

modules/ROOT/nav.adoc, modules/get-started/pages/cluster-types/serverless.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/manage/partials/controlplane-api.adoc, modules/reference/pages/tiers/index.adoc, modules/reference/pages/tiers/serverless-regions.adoc
This pull request adds supported regions for Serverless clusters. The changes include adding a new page for Serverless regions, updating references to these regions across various files, and enhancing descriptions for cluster creation.
* [`modules/reference/pages/tiers/serverless-regions.adoc`](diffhunk://#diff-5965ea26b4c5921a3afc0872272414398517542637a059a49c470af9d243d955R1-R24): Added a new page detailing supported regions for Serverless clusters, including AWS regions such as ap-northeast-1, ap-south-1, ap-southeast-1, eu-central-1, eu-west-2, us-east-1, and us-west-2.
* [`modules/ROOT/nav.adoc`](diffhunk://#diff-5daf5a85fd51578ad9fc545388bf62176bcea32094ee97b5e30c2eea044e4193R432): Added a new navigation entry for the Serverless Regions page under the Reference section.
* …
=> DOC-1415 add new AWS regions

modules/ROOT/nav.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/networking/pages/byoc/aws/transit-gateway.adoc
This pull request introduces documentation updates to support the new Amazon VPC Transit Gateway feature for BYOC and BYOVPC clusters on AWS. The changes include adding a dedicated page for setup instructions, updating navigation links, and highlighting the feature in the "What's New" section.
Please see the README edits here: https://github.com/redpanda-data/cloud-examples/pull/54
* **New dedicated page for Transit Gateway setup**:
Added `modules/networking/pages/byoc/aws/transit-gateway.adoc` with detailed instructions on setting up an Amazon VPC Transit Gateway, including an example using Terraform code from the Redpanda Cloud Examples repository.
* **Navigation update**:
Updated the `modules/ROOT/nav.adoc` file to include a link to the new Transit Gateway documentation under the AWS …
=> DOC-1335 AWS transit gateway

local-antora-playbook.yml, modules/ROOT/nav.adoc, modules/manage/pages/iceberg/iceberg-topics-databricks-unity.adoc
This pull request introduces updates to documentation related to Iceberg integration with Databricks Unity Catalog and modifies the Antora playbook configuration. The changes include adding new documentation pages, updating navigation links, and adjusting branch references in the playbook.
* [`modules/ROOT/nav.adoc`](diffhunk://#diff-5daf5a85fd51578ad9fc545388bf62176bcea32094ee97b5e30c2eea044e4193R401): Added a new navigation link for querying Iceberg topics with Databricks Unity Catalog.
* [`modules/manage/pages/iceberg/iceberg-topics-databricks-unity.adoc`](diffhunk://#diff-a8cc69134db34c0afe324812dbe0c1c9ec51c399f09a25e0c32d137913f81791R1-R5): Introduced a new documentation page for querying Redpanda topics as Iceberg tables in Databricks managed by Unity Catalog.
* …
=> Add Databricks pages in Cloud

modules/security/pages/cloud-encryption.adoc
This pull request updates the encryption protocol preferences and accepted cipher suites for TLS versions in the `modules/security/pages/cloud-encryption.adoc` file. The changes prioritize modern and secure configurations while removing support for older and less secure options.
* **TLSv1.2 Enhancements**:
- Added `Preferred TLSv1.2 128 bits ECDHE-RSA-AES128-GCM-SHA256` and `Accepted TLSv1.2 128 bits AES128-GCM-SHA256` to the list of supported cipher suites.
- Reintroduced `Accepted TLSv1.2 256 bits AES256-CCM` and `Accepted TLSv1.2 256 bits ECDHE-RSA-AES256-SHA`.
* **Removal of Legacy Support**:
- Removed all cipher suites for TLSv1.0 and TLSv1.1, including `Preferred TLSv1.0 256 bits ECDHE-RSA-AES256-SHA` and `Accepted TLSv1.1 128 bits AES128-SHA`.
- Dropped support for weaker TLSv1.2 …
=> DOC-1447 replace ciphersuites

local-antora-playbook.yml, modules/get-started/pages/cloud-overview.adoc
This pull request updates the `local-antora-playbook.yml` file to reflect changes in branch naming conventions and modifies the `cloud-overview.adoc` file to remove outdated information about beta features in Redpanda Cloud.
* [`local-antora-playbook.yml`](diffhunk://#diff-430ed78ec72afb78849cef359188c9b20a3dde4623593958cba0dfb974cb2ac9L18-R18): Changed the branch list for the `redpanda-data/documentation` repository to use `main` instead of the previously specific branch `DOC-1407-single-source-additions-for-Cloud`.
* [`modules/get-started/pages/cloud-overview.adoc`](diffhunk://#diff-10401c3a5fb2293775dd5cfed082eea9183cddd81dbd8664ab04e35c1f407b0bL257): Removed the mention of `rpk transform` being in beta for Redpanda Cloud, as this information is no longer relevant.
Resolves …
=> DOC-1448 update rpk transform in cloud overview

modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc
This docs PR proposes the following changes 
1. Remove default subnet as it collides with agent public egress subnet of 10.0.0.0/24 
2. Typo on Azure BYOVNET, quotations are somehow removed when using SHELL environment variables and interpolating them within a cat command. 
3. Define environment variables for use for creating networks and clusters.
4. Fix JSON request payload to work with new API schema.
=> BYOVnet improvements

modules/ROOT/nav.adoc
Navigation Update: Updated the link label in `modules/ROOT/nav.adoc` for consistency with other catalog integration docs.
=> Update navtree heading - Iceberg topics with Snowflake and Open Catalog

modules/get-started/pages/cluster-types/serverless.adoc, modules/get-started/pages/whats-new-cloud.adoc
This pull request removes the mention of the unsupported Schema Registry UI in the Serverless cluster limitations and adds a note about its availability in the "What's New" section.
Updates to Serverless cluster features:
* [`modules/get-started/pages/cluster-types/serverless.adoc`](diffhunk://#diff-b9ada45e986054dd3c87aefcc43f539e63aff7eb5e016458549138ad6445ac73L93): Removed the mention of the Schema Registry UI being unsupported in Serverless clusters.
Documentation additions:
* [`modules/get-started/pages/whats-new-cloud.adoc`](diffhunk://#diff-825e3d404929927e196111eaa92a310ee71d39aa9310418f56a55099a3a3f7c3R12-R15): Added a note in the "What's New" section announcing the availability of the Schema Registry UI for Serverless clusters.
Resolves …
=> DOC-1452 SR UI supported in Serverless

modules/get-started/pages/cluster-types/serverless.adoc, modules/get-started/pages/whats-new-cloud.adoc, modules/reference/pages/tiers/index.adoc
This pull request adds a new limit to the Serverless cluster documentation.
Documentation update:
* [`modules/get-started/pages/cluster-types/serverless.adoc`](diffhunk://#diff-b9ada45e986054dd3c87aefcc43f539e63aff7eb5e016458549138ad6445ac73R27): Added a new limit for "Connections" with a maximum of 10,000, under the "Each Serverless cluster has the following limits:" section.
Resolves https://redpandadata.atlassian.net/browse/DOC-1351
[Serverless usage limits](https://deploy-preview-340--rp-cloud.netlify.app/redpanda-cloud/get-started/cluster-types/serverless/#serverless-usage-limits)
=> DOC-1351 Serverless connection limit

modules/manage/pages/cluster-maintenance/config-cluster.adoc
Added a new "Prerequisites" section specifying the minimum Redpanda version required (25.1.2 or later) and instructions for verifying the `rpk` version.
Resolves https://redpandadata.atlassian.net/browse/DOC-1479
[Configure Cluster Properties - Prereqs](https://deploy-preview-342--rp-cloud.netlify.app/redpanda-cloud/manage/cluster-maintenance/config-cluster/)
=> DOC-1479 add rpk requirement for cluster config

modules/ROOT/nav.adoc, modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/byoc/azure/vnet-azure.adoc, modules/get-started/pages/cluster-types/byoc/gcp/vpc-byo-gcp.adoc, modules/get-started/pages/cluster-types/serverless.adoc, modules/manage/pages/monitor-cloud.adoc, modules/networking/pages/aws-privatelink.adoc, modules/networking/pages/dedicated/gcp/configure-psc-in-api.adoc, modules/networking/partials/psc-api2.adoc, modules/security/pages/cloud-encryption.adoc
This pull request includes a variety of documentation updates and corrections across multiple files, focusing on improving clarity, fixing typographical errors, and ensuring consistency in terminology. Below are the most important changes grouped by theme:
* Corrected the term "BYOC cluser" to "BYOC cluster" in `modules/networking/pages/aws-privatelink.adoc`.
* Standardized the term "DEDICATED" to "TYPE_DEDICATED" in `modules/networking/pages/dedicated/gcp/configure-psc-in-api.adoc`. [[1]](diffhunk://#diff-8ce1d72200c43317bd875941ec5b21f2e58c64ed8ed5b19f9532d3b189816409L40-R40) [[2]](diffhunk://#diff-8ce1d72200c43317bd875941ec5b21f2e58c64ed8ed5b19f9532d3b189816409L86-R86)
* Updated the description for creating a Redpanda cluster to clarify the JSON response in …
=> DOC-1487 apply coderabbit cloud-docs suggestions

modules/networking/pages/azure-private-link.adoc
We should be using the private dns subcommand instead of public.
=> Update azure-private-link.adoc - use private DNS command

modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc
This pull request updates the documentation for deploying BYOC clusters on Azure. The changes include adding instructions for setting up the Azure CLI and updating the VM size used in example commands and outputs.
* Added instructions for installing, signing in, and setting the subscription in the Azure CLI to ensure proper configuration before deploying a BYOC cluster. (`modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adoc`, [modules/get-started/pages/cluster-types/byoc/azure/create-byoc-cluster-azure.adocR15-R23](diffhunk://#diff-ab3280e96d3ffa280051aecc61f4c7f00de0e17b39e1d392895d15d6cd999dfaR15-R23))
* Updated the VM size in example commands and outputs from `Standard_D2ads_v5` to `Standard_D2d_v5` to reflect the correct VM size for deployment. …
=> DOC-1507. Add Azure CLI and Subscription

modules/networking/pages/cloud-security-network.adoc
This pull request updates the documentation in `modules/networking/pages/cloud-security-network.adoc` to clarify the network ports used for outgoing connections.
* Updated the network port information for the control plane, breakglass, artifact repository, and telemetry services to include both `443/tcp` and `80/tcp`.
Resolves https://redpandadata.atlassian.net/browse/DOC-1511
[Network ports](https://deploy-preview-360--rp-cloud.netlify.app/redpanda-cloud/networking/cloud-security-network/#network-ports)
=> DOC-1511 add south-north port

modules/ROOT/nav.adoc, modules/manage/pages/cluster-maintenance/cluster-state.adoc
This pull request introduces a new section to the documentation about cluster states, providing descriptions of various states for different cluster types (Serverless, BYOC, and Dedicated). 
* **Added a new "Cluster State" page**: This page explains the various states a cluster can be in, categorized by cluster types (Serverless, BYOC, Dedicated). It includes detailed descriptions of each state, such as "Creating," "Ready," "Suspended," and more.
* **Updated navigation to include the "Cluster State" page**: Added a new entry under the "Cluster Maintenance" section in the navigation (`modules/ROOT/nav.adoc`).
Resolves https://redpandadata.atlassian.net/browse/DOC-241
[Cluster State](https://deploy-preview-323--rp-cloud.netlify.app/redpanda-cloud/manage/cluster-maintenance/c …
=> DOC-241 doc all possible cluster states

modules/manage/partials/controlplane-api.adoc
Resolves https://github.com/redpanda-data/cloud-docs/issues/273
=> docs: fix serveless example

modules/get-started/pages/whats-new-cloud.adoc
=> Fix heading for AWS Glue entry

modules/ROOT/nav.adoc, modules/develop/pages/connect/about.adoc, modules/develop/pages/connect/components/about.adoc, modules/develop/pages/connect/components/catalog.adoc, modules/develop/pages/connect/configuration/contextual-variables.adoc, modules/develop/pages/connect/connect-quickstart.adoc, modules/get-started/pages/cluster-types/byoc/gcp/enable-rpcn-byovpc-gcp.adoc, modules/get-started/pages/whats-new-cloud.adoc
- Show component catalog table immediately when clicking Components
- Update navigation and fix all cross-references
- Align with user expectations for catalog functionality
Resolves https://redpandadata.atlassian.net/browse/DOC-1553
This pull request updates the documentation for Redpanda Connect by consolidating and simplifying the connector catalog pages, removing redundancy, and updating all references to the connector catalog throughout the docs. The changes ensure that users are directed to the correct and up-to-date catalog location and improve navigation consistency.
Documentation structure and navigation updates:
* Removed the redundant `catalog.adoc` file and merged its content and references into `about.adoc`, now renamed and aliased as "Components Catalog" for clarity and …
=> DOC-1553 Improve components navigation UX by defaulting to catalog

modules/develop/pages/connect/configuration/resource-management.adoc, modules/develop/pages/connect/configuration/secret-management.adoc
**Secret Management Documentation Improvements:**
* Unified and simplified Cloud UI instructions for creating, updating, and deleting secrets, removing cluster-type distinctions and referencing the new **Secrets Store** page. [[1]](diffhunk://#diff-d05f7a44ad76ec93bcb30759c7a1c0a7c4a3d78366535dce45a73dadb711803dL6-R30) [[2]](diffhunk://#diff-d05f7a44ad76ec93bcb30759c7a1c0a7c4a3d78366535dce45a73dadb711803dL100-R80) [[3]](diffhunk://#diff-d05f7a44ad76ec93bcb30759c7a1c0a7c4a3d78366535dce45a73dadb711803dL164-R130)
* Updated instructions for adding secrets to pipelines, including a new quick-add **Secret** button in the Cloud UI and clearer API usage examples.
**Resource Management Prerequisites:**
* Simplified the cluster prerequisites by removing references to cluster types BYOVPC/BYOVNet, …
=> DOC-1401 RPCN Secrets navigation change in UI

modules/manage/pages/terraform-provider.adoc
This pull request adds a warning advising users not to modify the `throughput_tier` after it is set, as this action will tear down and rebuild the cluster.
Resolves https://redpandadata.atlassian.net/browse/DOC-1577
[Redpanda Terraform Provider Limitations](https://deploy-preview-387--rp-cloud.netlify.app/redpanda-cloud/manage/terraform-provider/#limitations)
=> DOC-1577 add warning to not modify throughput_tier

modules/get-started/pages/cloud-overview.adoc, modules/manage/pages/monitor-cloud.adoc
* Updated references to "metrics" across multiple files to explicitly specify "Redpanda metrics," ensuring clarity about the scope of exported metrics. (`modules/get-started/pages/cloud-overview.adoc`, `modules/manage/pages/monitor-cloud.adoc`) [[1]](diffhunk://#diff-10401c3a5fb2293775dd5cfed082eea9183cddd81dbd8664ab04e35c1f407b0bL102-R102) [[2]](diffhunk://#diff-ba3ed8303d1d86cdac3ea60ded83aca4c4eb92b5a4eb0f8308fe5cb9aa98a0e5L39-R44) [[3]](diffhunk://#diff-ba3ed8303d1d86cdac3ea60ded83aca4c4eb92b5a4eb0f8308fe5cb9aa98a0e5L66-R71)
* Moved the description of the Prometheus endpoint to a more prominent location and clarified that it exports Redpanda metrics for brokers and Kafka Connect workers. Also added a note about the unavailability of OS-level and node-level metrics and recommended …
=> DOC-1070 Prometheus endpoint scrapes Redpanda metrics

modules/ROOT/nav.adoc, modules/get-started/pages/cluster-types/byoc/gcp/create-byoc-cluster-gcp.adoc, modules/get-started/pages/cluster-types/byoc/gcp/vpc-byo-gcp.adoc, modules/manage/partials/controlplane-api.adoc, modules/networking/pages/aws-privatelink.adoc, modules/networking/pages/azure-private-link.adoc, modules/networking/pages/byoc/gcp/enable-global-access.adoc, modules/networking/pages/dedicated/gcp/configure-psc-in-api.adoc, modules/networking/pages/gcp-private-service-connect.adoc, modules/networking/partials/private-links-api-access-token.adoc, modules/networking/partials/psc-ui.adoc
This pull request introduces documentation for enabling global access for BYOC and BYOVPC clusters on GCP, and standardizes API example request bodies across multiple cloud providers by wrapping resources in top-level keys. The changes improve clarity and consistency in API usage, and guide users on how to enable global access for cross-region client connectivity.
**Global Access Enablement Documentation:**
* Added a new guide, `enable-global-access.adoc`, detailing how to enable global access for BYOC and BYOVPC clusters on GCP using the Redpanda Cloud API, including prerequisites, limitations, and step-by-step instructions for both cluster types.
* Updated navigation (`nav.adoc`) and relevant getting started pages to reference the new guide, ensuring users are directed to global access …
=> Enable GCP global access

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/byoc/gcp/enable-rpcn-byovpc-gcp.adoc, modules/get-started/pages/cluster-types/byoc/index.adoc, modules/networking/pages/byoc/gcp/vpc-peering-gcp.adoc
This pull request adds introductory info for BYOC/BYOVPC/BYOVNet for people landing on the BYOC index page from the new [Get started with BYOC link](https://docs.redpanda.com/home/) on our docs home page. 
Resolves https://redpandadata.atlassian.net/browse/DOC-95
=> DOC-95 add get started for BYOC

modules/security/pages/cloud-authentication.adoc
This pull request updates the Redpanda Cloud authentication documentation for clarity and accuracy around integrating with Microsoft Entra ID. Updated and expanded the Microsoft Entra ID integration instructions to emphasize the need for the app to be configured as *Web* (not SPA or mobile), due to the OIDC Authorization Code flow with PKCE and server-side callback. Added note detailing claims, API permissions, and consent behavior, plus troubleshooting tips for common issues.
Resolves https://redpandadata.atlassian.net/browse/DOC-1269
[SSO - Integrate with Microsoft Entra ID](https://deploy-preview-392--rp-cloud.netlify.app/redpanda-cloud/security/cloud-authentication/#integrate-with-microsoft-entra-id)
=> DOC-1269 Clarify SSO with Entra ID

modules/manage/pages/cluster-maintenance/config-cluster.adoc
This PR modifies a code example that uses a secret in rpk cluster config set. Single quotes are added around the secret to ensure that the shell doesn't try to interpret the secret as a variable, and the secret value gets passed into the cluster config correctly.
=> Enclose secret in single quotes

modules/develop/pages/data-transforms/build.adoc, modules/get-started/pages/cloud-overview.adoc
This pull request clarifies the differences between Redpanda Connect and data transforms, helping users choose the right tool for their data pipeline needs. It adds a new comparison table and explanatory tips to highlight use cases, capabilities, and limitations of each feature.
* Added a detailed comparison table and explanation of Redpanda Connect vs data transforms in `modules/get-started/pages/cloud-overview.adoc`
* Added a new tip to `modules/develop/pages/data-transforms/build.adoc` explaining that data transforms are best for lightweight, in-broker data prep, while Redpanda Connect should be used for external integrations, batching, and prebuilt processors.
Resolves https://redpandadata.atlassian.net/browse/DOC-1575
[Cloud …
=> DOC-1575 RPCN vs Wasm decision matrix

modules/get-started/pages/cloud-overview.adoc, modules/get-started/pages/cluster-types/serverless.adoc, modules/security/pages/authorization/rbac/rbac_dp.adoc
This pull request clarifies the availability of role-based access control (RBAC) in the data plane for Serverless. 
* Added explicit mention that RBAC in the data plane is available for BYOC and Dedicated clusters in `modules/security/pages/authorization/rbac/rbac_dp.adoc`.
* Updated the feature list for BYOC and Dedicated clusters in `modules/get-started/pages/cloud-overview.adoc` to include RBAC in the data plane.
* Clarified and reordered features for Serverless clusters in `modules/get-started/pages/cluster-types/serverless.adoc`, ensuring RBAC and mTLS authentication are listed, and adjusted the placement of Kafka Connect for consistency.
Resolves https://redpandadata.atlassian.net/browse/DOC-1646
[Cloud Overview](https://deploy-preview-403--rp-cloud.netlify.app/redpa …
=> DOC-1646 RBAC in DP not supported for Serverless

modules/networking/pages/aws-privatelink.adoc
This PR updates the AWS PrivateLink networking doc for adding security group rules. 
* Updated instructions to recommend opening the full port ranges (`32000-32500` for Kafka API and `35000-35500` for HTTP Proxy) instead of specifying ports based on broker count, improving reliability for all cluster sizes.
* Added a note explaining why opening only a subset of ports can break producers/consumers, with a reference to doc on network ports.
* Updated example `aws ec2 authorize-security-group-ingress` commands to match the new guidance, including more descriptive comments and grouping for bootstrap, Schema Registry, HTTP Proxy, and per-broker port pools.
Resolves https://redpandadata.atlassian.net/browse/DOC-1651
[Add security group …
=> DOC-1651 update AWS VPC endpoints security group ports

modules/networking/pages/aws-privatelink.adoc, modules/networking/pages/azure-private-link.adoc, modules/networking/pages/byoc/aws/vpc-peering-aws.adoc, modules/networking/pages/byoc/gcp/vpc-peering-gcp.adoc, modules/networking/pages/dedicated/aws/vpc-peering.adoc, modules/networking/pages/dedicated/gcp/configure-psc-in-api.adoc, modules/networking/pages/dedicated/gcp/vpc-peering-gcp.adoc, modules/networking/pages/gcp-private-service-connect.adoc, modules/networking/partials/switch-to-psc.adoc, modules/networking/partials/vnet-peering.adoc
This pull request updates the networking doc to add how to switch from VPC peering to PrivateLink or Private Service Connect. 
- Added new "Switch from VPC peering to PrivateLink" and "Switch from VPC peering to Private Service Connect" sections in AWS and GCP BYOC and Dedicated guides, describing a staged DNS switchover process to avoid client disruption. [[1]](diffhunk://#diff-b6be944b1a3e47d87b4d599ff8f5ee996e45a74685085d494c0452aea4ff0ba2R61-R69) [[2]](diffhunk://#diff-b8107479b8960f8bacce20835cd01ca4da484da90afa57c99cd1d72d54ad3325R44-R52) [[3]](diffhunk://#diff-dac3575a8d3782538a0aa5cda85e6ed63def8fa15a079115aeb1577f4036b59eR45-R55) [[4]](diffhunk://#diff-3cb0cb07f72cd75c6fb5f7c9bacf8193c166168a33beaec4d56e8cc1fe4159d0L20-R47)
- Updated warnings for enabling PrivateLink and Private …
=> DOC-1652 change from VPC peering to PSC

modules/ROOT/nav.adoc, modules/develop/pages/connect/components/scanners/json_array.adoc
This PR single-sources the content for the new `json_array` scanner into Redpanda Cloud. The original content was introduced in https://github.com/redpanda-data/rp-connect-docs/pull/304
=> Add JSON array scanner
